### ISSUE TITLE
obContentUrl doesn't support

### ISSUE THREAD

**Issue by VictoriaKirichenko** [outbrain/react-outbrain-widget#16]
I'm trying to implement a new widget format, but the **data-ob-contenturl** attribute doesn't add to div at all.
Therefore my widget is not loading.

`        <OutbrainWidget
          obContentUrl={ `https://${domain}/${permalink}` }
          dataWidgetId={widgetId}
          obInstallationKey={installationKey}
        />
`

node_modules\react-outbrain-widget\build\index.js looks like doesn't contain such attribute at all: 
![image](https://user-images.githubusercontent.com/16206726/115150222-2a379880-a070-11eb-8238-466359209ed5.png)

![image](https://user-images.githubusercontent.com/16206726/115150820-b945b000-a072-11eb-80bd-dedc8be10c26.png)

**Comment by tomerlevy1** [comment]
hi @VictoriaKirichenko 
thanks for bringing this to our attention
we published version 1.2.2 that should resolve the issue
