### ISSUE TITLE
@types/react-outbrain-widget Not found

### ISSUE THREAD

**Issue by hofitAdady** [outbrain/react-outbrain-widget#36]
We are trying to install the react-outbrain-widget library on react-typescript app 
we are getting this error: 
_" Could not find a declaration file for module 'react-outbrain-widget'. 
Try `npm i --save-dev @types/react-outbrain-widget` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-outbrain-widget';`ts(7016)"_

When we try to add the @types/react-outbrain-widget we get this error 
_"https://registry.yarnpkg.com/@types%2freact-outbrain-widget: Not found"_

Do you familiar with this issue? 

Any help will help :) 
Thanks

**Comment by obaglazer** [comment]
Hi @hofitAdady,
can you try and import the package with require instead of import?
const { OutbrainWidget } = require('react-outbrain-widget');

Please update if it helped

**Comment by hofitAdady** [comment]
Hey, 
Thank you for your replay
This solution is good but It has eslint error 
so I have created type declaration file for the OutbrainWidget

**Comment by jeromecovington** [comment]
@hofitAdady can you please share your type declaration file?

**Comment by hofitAdady** [comment]
the file should be on @type folder and with .d, for example: 
_/@types/typeOutbrain.d.ts_

declare module 'react-outbrain-widget' {
  import * as React from 'react';

  export interface OutbrainWidgetProps {
    //put here the properties you are going to use on the widget 
  }

  export const OutbrainWidget: React.FC<OutbrainWidgetProps>;

}
